### PR TITLE
Solved #49, Bottom Navigation Bar Bug fixed.

### LINKED ISSUE #49: Bug in Bottom Navigation Bar
Current page get pushed on itself on clicking that page icon in Bottom Navigation bar, thus clicking back button does opens up the previous page, this is a bug and need fixing.
I can fix this bug So I request you to assign this issue to me.

https://user-images.githubusercontent.com/106864146/195773640-fe257f6e-4297-4695-92ce-6f72ef39e61d.mp4

### PR DESCRIPTION
**Pull request by shazebK**
Resolves #49 
@RitwikSingh28 
I have fixed the bottom navigation bar bug by using pushReplacement and making back button to directly take user to homepage.

### CODE REVIEW

File: lib/individual/info_page.dart [hunk 1]
```diff
@@ -24,7 +25,7 @@ class _IndividualInfoPageState extends State<IndividualInfoPage> {
               color: Colors.black,
               size: MediaQuery.of(context).size.height * 0.025),
           leading: IconButton(
-            onPressed: () => Navigator.of(context).pop(),
+            onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (context) => const HomePageIndividual())),
```
Comment (RitwikSingh28) [inline lib/individual/info_page.dart:28]: This concept of pushing the Home Page upon clicking the Back Arrow button, does fix the issue. But it also includes many performance issues :thinking: . For now, this is alright, but we will need to change this to popUntil when we implement named-routing in our application.
